In [1]:
import numpy as np

In [2]:
myNpList = np.array([1,2,3,4,5])

In [3]:
type(myNpList)

numpy.ndarray

In [4]:
myNpList.max()

np.int64(5)

In [5]:
myList = [10,20,30,40]

In [6]:
myNpList2 = np.array(myList)

In [7]:
myNpList2.max()

np.int64(40)

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random(5)

array([0.03682246, 0.43533657, 0.56587698, 0.77109091, 0.47554229])

In [12]:
# array aritmetic

In [13]:
myList = [1,2]
myList2= [2,3]

myList + myList2

[1, 2, 2, 3]

In [17]:
# addition difference between normal list and numpy list
myNpList = np.array(myList)
myNpList2 = np.array(myList2)

myNpList + myNpList2 

array([3, 5])

In [18]:
myNpList * myNpList2 

array([2, 6])

In [19]:
nArr = np.array([10,20,30,40])

In [21]:
int(nArr.min())

10

In [22]:
int(nArr.sum())

100

In [23]:
# arange & indexing

In [24]:
list (range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
npArr = np.arange(0,10)

In [28]:
npArr[0]

np.int64(0)

In [29]:
int(npArr[-1])

9

In [30]:
npArr[1:7:2]

array([1, 3, 5])

In [31]:
npArr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
# random

In [33]:
np.random.randn(3,3)

array([[ 0.95771173, -0.60538115,  1.74895706],
       [ 0.7696441 , -1.22025365,  0.14548971],
       [ 0.55511269, -2.42333879,  0.42415457]])

In [34]:
np.random.randint(1,300,5)

array([215, 244,  42,  46,  64], dtype=int32)