In [1]:
import numpy as np

In [2]:
myMtrx = np.random.randint(1,20,2)

In [3]:
myMtrx

array([ 7, 13], dtype=int32)

In [4]:
myMtrx = np.random.randn(2,2)

In [5]:
myMtrx

array([[0.15352899, 0.68389814],
       [1.98534853, 2.29656592]])

In [7]:
help(np.random.randn)

Help on method randn in module numpy.random.mtrand:

randn(*args) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the dis

In [8]:
myMtrx = 2 + np.random.randn(2,2)

In [9]:
myMtrx

array([[3.09255062, 0.38651393],
       [1.89678095, 2.44776866]])

In [10]:
# row * column

In [13]:
npMatrix = np.array([[5,10],[15,20],[25,30]])

In [14]:
npMatrix

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [16]:
int(npMatrix[2][0])

25

In [17]:
npMatrix.sum()

np.int64(105)

In [18]:
npMatrix.min()

np.int64(5)

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.random.random((2,2))

array([[0.11481424, 0.04150287],
       [0.0937066 , 0.54661686]])

In [27]:
np.random.random((2,2))+ np.random.random((2,2))

array([[0.69060121, 1.30690672],
       [0.80564088, 1.82861518]])

In [28]:
# matrix multiplication

In [29]:
fArr = np.array([[5,15],[25,35]])

In [30]:
fArr2 = np.array([[10,20],[30,40]])

In [31]:
fArr * fArr2

array([[  50,  300],
       [ 750, 1400]])

In [32]:
fArr = np.array([[1,2,3]])

In [33]:
fArr.shape

(1, 3)

In [40]:
sArr = np.array([[1,3],[3,5],[2,7]])

In [41]:
sArr.shape

(3, 2)

In [42]:
result=fArr.dot(sArr)

In [43]:
print(result)

[[13 34]]


In [44]:
result.shape

(1, 2)