In [1]:
import numpy as np

In [2]:
nArr = np.random.randint(1,100,20)

In [3]:
nArr

array([25, 40, 64, 28,  8, 25, 98,  1, 47, 22, 68, 77, 70, 68, 76, 14, 55,
       27, 16, 83], dtype=int32)

In [4]:
nArr[nArr > 25]

array([40, 64, 28, 98, 47, 68, 77, 70, 68, 76, 55, 27, 83], dtype=int32)

In [5]:
nArr[nArr < 25]

array([ 8,  1, 22, 14, 16], dtype=int32)

In [6]:
# transpose & reshape

In [7]:
mArr = np.array([[10,20],[20,30],[30,40]])

In [8]:
mArr

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
mArr.shape

(3, 2)

In [11]:
mArr.transpose() # mArr.T is same 

array([[10, 20, 30],
       [20, 30, 40]])

In [12]:
randArr = np.random.random((6,1))

In [13]:
randArr

array([[0.19830103],
       [0.98241612],
       [0.02219335],
       [0.81362643],
       [0.41607453],
       [0.63441633]])

In [14]:
randArr.shape

(6, 1)

In [15]:
randArr.reshape(2,3)

array([[0.19830103, 0.98241612, 0.02219335],
       [0.81362643, 0.41607453, 0.63441633]])

In [16]:
# z-score

In [17]:
data = np.array([10,12,13,15,18,25,100,105])

In [18]:
# outlier

In [25]:
mean = np.mean(data) # ort

In [26]:
mean

np.float64(37.25)

In [27]:
std = np.std(data) # standart sapma

In [28]:
std

np.float64(37.9333296719389)

In [29]:
zScore = (data - mean) / std

In [30]:
zScore

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [31]:
data[zScore > 1] # checking outliers manually

array([100, 105])

In [32]:
# math equations

In [33]:
# 2x + 3y =8 and 5x + 7y = 19

In [34]:
#coefficient

In [35]:
A = np.array([[2,3],[5,7]])

In [36]:
#constant

In [37]:
b = np.array([8,19])

In [38]:
solution = np.linalg.solve(A,b)

In [39]:
solution

array([1., 2.])

In [40]:
# x = 1, y = 2 is correct